### ISSUE TITLE
CSS Nesting recipe

### ISSUE THREAD

**Issue by sandstrom** [skovy/css-codemod#9]
Thanks for an awesome project! 🏅 

Maybe a nesting recipe would be a good addition to recipes?

I think that's something a lot of people will want to do, when converting from SCSS to native CSS (or postCSS).

Some more background:
- https://kilianvalkhof.com/2021/css-html/css-nesting-specificity-and-you/
- https://drafts.csswg.org/css-nesting-1/
- https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-nesting

There is already a `postcss-nesting` that could probably use used as a starting point.

**Comment by skovy** [comment]
@sandstrom a contribution with an example recipe for this makes sense to me. I won't have time to work on it, but I'd be open to accepting a contribution.

**Comment by sandstrom** [comment]
@skovy I'll see if I can figure it out.

Feel free to close this issue at any time though.
